name: model_select 
channels:
  - https://repo.anaconda.com/pkgs/free
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.11
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.24.2
  - pip=19.1.1
  - python=3.6.8
  - snakemake=3.13.3
  - pip:
    - black==19.3b0
    - dynesty==1.0.0
    - h5py==2.10.0
    - periodictable==1.5.0
    - refnx==0.1.7
    - seaborn==0.9.0
    - uncertainties==3.1.2